---
title: "News"
---

+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date           | News                                                                                                                                                                                                                                                                                                                                                                        |
+================+=============================================================================================================================================================================================================================================================================================================================================================================+
| August 2024    | Attended [*Analyzing Neural Time Series* Summer School](https://sincxpress.com/summerschool.html) with Mike X Cohen in Bucharest, Romania. \| **July 29 - August 2, 2024**                                                                                                                                                                                                  |
+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| July 2024      | Awarded a [Alexander von Humbodlt Post-doctoral Fellowship](https://www.humboldt-foundation.de/en/apply/sponsorship-programmes/humboldt-research-fellowship) to fund my work on *Decision-Making Strategies in Aging Adults*. \| **October 2024 - October 2025 \| \                                                                                                         |
|                | *19,200 EUR as research funds***                                                                                                                                                                                                                                                                                                                                            |
+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| June 2024      | Received [Ideas and Venture Fund Grant](https://www.uni-hamburg.de/en/exzellenz/fuenf-zentrale-themen/forschung/ideen-und-risikofonds.html#:~:text=In%202024%2C%20for%20the%20first,projects%20in%20individual%20funding%20programs.) from the University of Hamburg to fund my work on *Credit Assignment in Aging Adults*. \| **June 2024 - October 2025 \| *50,000 EUR*\ |
|                | **\*co-awarded to Dr. Xiangjuan Ren                                                                                                                                                                                                                                                                                                                                         |
+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| May 2024       | Attended [Pug 2024 Conference](https://pug2024.de/) in Hamburg, Germany. \| **May 29 - June 1**                                                                                                                                                                                                                                                                             |
+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| March 2024     | Presented "Diminished State Space Theory of Human Aging" at [TeAP 2024](https://conference-service.com/teap-2024-regensburg/access.html), Regensburg, Germany. \| **March 18, 2024**                                                                                                                                                                                        |
+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| November 2023  | ["Diminished State Space Theory of Human Aging"](https://journals.sagepub.com/doi/pdf/10.1177/17456916231204811) paper accepted for publication in Perspectives on Psychological Science.                                                                                                                                                                                   |
+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| September 2023 | Started as a Post-doctoral Researcher in the [Schuck Lab](https://schucklab.gitlab.io/) at the University of Hamburg, Germany. \| **September 2023 - September 2026**                                                                                                                                                                                                       |
+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| August 2023    | Successfully defended PhD under the supervision of [Dr. Ben Eppinger at Concordia University](http://www.ldmlab.org/), Montreal, Canada. \| **August 28, 2023**                                                                                                                                                                                                             |
+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| December 2022  | Received Knowledge Mobilization Award from [EngAGE at Concordia University](https://www.concordia.ca/research/aging/about.html)                                                                                                                                                                                                                                             |
+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| November 2022  | Gave an accessible talk at [Univesity Women's Club Montreal](https://uwcm.com/) about Decision-Making in Older Adults \| **November 16, 2022**                                                                                                                                                                                                                              |
+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| May 2022       | Research Competition, 3rd place. Awarded by [EngAGE at Concordia University](https://www.concordia.ca/research/aging/about.html)                                                                                                                                                                                                                                            |
+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| August 2021    | Attended [ComSciCon Flagship Workshop](https://www.comscicon.org/) 2021 \| **August 4-7, 2021**                                                                                                                                                                                                                                                                             |
+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| August 2021    | Featured in [Concordia University's Magazine](https://www.concordia.ca/content/dam/concordia/aar/docs/magazine/2021-Fall-Concordia_University_Magazine.pdf) for Fall 2021: Everything you need to know about... Decision-Making in older adults                                                                                                                             |
+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| May 2021       | Scientific Citizenship Award from Concordia University, Psychology Department.                                                                                                                                                                                                                                                                                              |
+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| December 2020  | [Public Scholar](https://www.concordia.ca/gradstudies/professional-skills/public-scholars/alumni/2021.html) (Science Communication Trainning) at Concordia University                                                                                                                                                                                                       |
+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| July 2020      | Received a [Post-Graduate Scholarship (Doctoral)](https://www.nserc-crsng.gc.ca/students-etudiants/pg-cs/bellandpostgrad-belletsuperieures_eng.asp) from the Natural Sciences and Engineering Research Council of Canada (NSERC) \| **September 2020 - September 2023**                                                                                                     |
+----------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[8,25\]"}
