---
title: "Science Communication"
---

## Accessible Talks

#### Careers Outside Academia

A discussion with Concordia University Alumni who "left" academia to succeed in industry. \| **November 18, 2021**\| Listen to the discussion [here](https://www.youtube.com/watch?v=RwbO9DR7ecY).

#### Decision Making and the Brain

Round-Table Discussion with Nathaniel Daw, Yael Niv, Oriel FeldmanHall & Anne Collins\| **September 19, 2021**\| Watch the discussion [here](https://www.youtube.com/watch?v=M0neJU1pH7w&t=3278s).

#### "In the Spotlight" Podcast: Decision-Making

A podcast interview on why we make the decisions we do, and how do our experiences guide them. \| **September 2021** \| Listen to the episode [here](https://open.spotify.com/episode/75K8MbQGAi9Eccp2TsFjfu).

#### Radio Interview on Montreal NOW with Aaron Rand and Natasha Hall

A radio interview on cjad800 Montreal about the implications of my work on aging adults. \| **July 23, 2021** \| Listen to the interview [here](https://omny.fm/shows/cjad-800/we-need-to-make-technology-more-accessible-to-seni?in_playlist=front-page).

#### Decision-Making and Metacognition

An accessible discussion on decision-making featuring a high school student who provides a fresh perspective. \| **June 2021** \| Listen to the discussion [here](https://open.spotify.com/episode/2WYL10jfRowBhxOdz6cWRO?si=UEipl528QdqR7OVihhDRxQ&nd=1&dlsi=eb964bc0fcbb42f7).

## Blog Posts & Articles

[**Web Magazine Article:**]{.underline} **Being a 55-plus homeowner is all about possibilities** \| **April 1, 2025** \|\
*"Our homes are, for many of us, not only the single biggest financial investment of our lives but also the embodiment of who we are. Those two factors can make decisions about where and how we live intimidating, even paralyzing as we age and become more set in our ways,*"\
Read it [here](https://allthingshome.ca/new-homes/articles/article/being-a-55-plus-homeowner-is-all-about-possibilities/).

[**Blog:**]{.underline} **How to Avoid Biting off more than you can Chew** \| **February 10, 2022** \|\
*"We've all been there; your professor asks you to do something and, without batting an eye you say,"I'll have that done by this afternoon, no problem." Yet, once you start working on it, you realize there is no way you will finish on time."*\
Read it [here](https://www.concordia.ca/cunews/offices/vprgs/sgs/public-scholars-21/2022/02/10/how-to-avoid-biting-off-more-than-you-can-chew.html).

[**Career Column:**]{.underline} **Our mentoring plan was a lifeline and it's still going \| November 25, 2021 \|**\
*"PsychOut sessions took the form of one-on-one virtual meetings every two weeks throughout the 2020 school year, at which the secondary-school students followed the progress of the undergraduate mentors' research projects."*

[**Blog**]{.underline}**: A letter to my past self** \| **August 12, 2021** \|\
"*Dear past self,\
Although you don't think you do, you got this."*\
Read it [here]().

[**Opinion:**]{.underline} **It's time seniors had technology tailored to them \| July 21, 2021 \|\
***"Without technology tailored to our seniors, we will be leaving a considerable proportion of older adults behind and at risk of social isolation."\
*Read it [here](https://montrealgazette.com/opinion/opinion-its-time-seniors-had-technology-tailored-to-them).

[**Blog:**]{.underline} **Deciding, choosing, and learning: What's the difference?** \| **June 4, 2021** \|\
*"In my world, deciding is different from choosing but similar to learning, and here is why."*\
Read it [here]().

[**Blog:**]{.underline} **Deciding what to decide is no easy task** \| **May 13, 2021** \|\
*"With warm and sunny days becoming more frequent, do you struggle to stay motivated to work throughout the day? I sure do!"*\
Read it [here]().

## Leadership

**Outreach Events in Local HighSchools (NSERC Ambassador's Award Event)** \| Organizer & Presenter \| November/December 2021

**CSBBCS Conference 2021** \| Student Organizer \| June 2021

**Concordia's Journal of Psychology & Neuroscience (CJPN)**\| Co-Founder \| 2021

**Concordia's Journal of Accessible Psychology (CJAP)**\| Founder & Editor-in-Chief \| 2019-2020
